module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#191c1e",
        "on-primary-fixed": "#00174b",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-container-low": "#f2f3ff",
        "outline-variant": "#c3c6d7",
        "inverse-primary": "#b4c5ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#57657a",
        "inverse-on-surface": "#eef0ff",
        "on-secondary-fixed": "#0d1c2e",
        "secondary-fixed-dim": "#b9c7df",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        secondary: "#515f74",
        "tertiary-fixed": "#e0e3e5",
        "secondary-container": "#d5e3fc",
        "on-tertiary-container": "#eff1f3",
        "tertiary-container": "#6b6e70",
        "on-surface-variant": "#434655",
        tertiary: "#525657",
        primary: "#004ac6",
        "surface-dim": "#d2d9f4",
        "surface-container-high": "#e2e7ff",
        "error-container": "#ffdad6",
        background: "#faf8ff",
        "primary-container": "#2563eb",
        surface: "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#eeefff",
        "surface-bright": "#faf8ff",
        error: "#ba1a1a",
        "surface-container": "#eaedff",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed-variant": "#444749",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d5e3fc",
        "surface-container-highest": "#dae2fd",
        "inverse-surface": "#283044",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary": "#ffffff",
        "surface-variant": "#dae2fd",
        outline: "#737686",
        "surface-tint": "#0053db",
        "primary-fixed-dim": "#b4c5ff",
        "on-background": "#131b2e",
      },
      fontFamily: {
        "headline-lg": ["Inter_600SemiBold"],
        display: ["Inter_700Bold"],
        "label-md": ["Inter_500Medium"],
        "label-sm": ["Inter_600SemiBold"],
        "body-lg": ["Inter_400Regular"],
        "headline-md": ["Inter_600SemiBold"],
        "body-md": ["Inter_400Regular"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        display: ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        base: "8px",
        gutter: "12px",
        lg: "24px",
        xl: "32px",
        "container-margin": "16px",
      },
    },
  },
};
